baseURL: "https://shenlong616.github.io/"
buildDrafts: false
buildExpired: false
buildFuture: false
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
paginate: 5
publishDir: ".."
pygmentsUseClasses: true
theme: PaperMod
title: Shenlong616
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: home
      name: home
      weight: 1

    - identifier: archives
      name: archives
      url: /archives/
      weight: 2

    - identifier: tags
      name: tags
      url: /tags/
      weight: 3

    - identifier: categories
      name: categories
      url: /categories/
      weight: 4

    - identifier: search
      name: search
      url: /search/
      weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  # author: ["Me", "You"] # multiple authors
  # author: Theme PaperMod
  # CanonicalLinkText: "Originally published at"
  # comments: false
  # disableSpecial1stPost: true
  # images: ["papermod-cover.png"] # Link or path of image for opengraph, twitter-cards
  defaultTheme: auto # auto, light, dark
  description: "Shenlong's blog!"
  disableThemeToggle: false
  displayFullLangName: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords:
    [blog, javascript tips, javascript tricks, python tips, python tricks, dev]
  math: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  ShowPostNavLinks: true
  ShowReadingTime: false
  ShowRssButtonInSectionTermList: true
  ShowShareButtons: false
  ShowToc: true
  ShowWordCount: false
  TocOpen: true

  schema:
    publisherType: "Person"
    sameAs: ["https://shenlong616.github.io/"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120

    buttons:
      - name: Archives
        url: archives

      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Xin Chào 👋"
    Content: "void(0)"

  socialIcons:
    - name: GitHub
      url: "https://github.com/Shenlong616"

    - name: RSS
      url: "index.xml"

    # - name: customURL
    #   url: "#"

  editPost:
    URL: "https://github.com/Shenlong616/Shenlong616.github.io/tree/main/_dev/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "AzXCkO0tq4MO96bDYSrwJRKKCYqk92c1N2Yere6jdxc"
    bing:
      SiteVerificationTag: "24E5C745EF8D6815F97FBCACA22956C9"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"
    # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource--
    disableFingerprinting: true

  cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.8
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true

  twitter:
    disableInlineCSS: true
